name: basic_fastapi_ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PORT: ${{ secrets.PORT }}
jobs:
  test:
    strategy:
      matrix:
        operatin-system: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    environment: test_env
    env:
      PORT: ${{secrets.PORT}}
      PASSWORD: "tak_navazan"
    runs-on: ${{matrix.operatin-system}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: installing Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: running tests
        run: |
          echo "pytest statrted"
          pytest -v
          echo "pytest ended"
      - name: uploading test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}-${{ matrix.operatin-system }}
          path: test_result.txt
      - name: printing envs
        run: |
          echo "PORT: ${{env.PORT}}"
          echo "PASSWORD: ${{env.PASSWORD}}"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: installing Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: building project
        run: |
          echo "Building the project"
      - name: printing envs
        run: |
          echo "PORT: ${{env.PORT}}"
          echo "PASSWORD: ${{env.PASSWORD}}"
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: installing Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: running project
        run: |
          echo "Running the project"
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}-${{ matrix.operatin-system }}
