name: basic_fastapi_ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: installing Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: running tests
        run: |
          echo "pytest statrted"
          pytest -v
          echo "pytest ended"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: installing Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: building project
        run: |
          echo "Building the project"
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: installing Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: running project
        run: |
          echo "Running the project"
